# Generated by Django 5.0.6 on 2024-07-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polling_station", "0002_alter_pollingstation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollingstation",
            old_name="registeredVoters_count",
            new_name="registered_voters_count",
        ),
    ]
