# Generated by Django 5.0.6 on 2024-06-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_voter",
            field=models.BooleanField(default=True),
        ),
    ]
