# Generated by Django 5.0.6 on 2024-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2021/07/25/08/03/account-6491185_1280.png'),
        ),
    ]
