# Generated by Django 5.0.6 on 2024-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='county_number',
            field=models.CharField(default=0, max_length=3, unique=True),
        ),
    ]
