# Generated by Django 5.0.6 on 2024-09-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("county", "0002_county_county_number"),
        ("laws", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ward", models.CharField(max_length=20, unique=True)),
                (
                    "constituency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="county.constituency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Senator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "bill_proposed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="laws.bill"
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="county.county"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
