# Generated by Django 5.0.6 on 2024-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_voter_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$xp3Yv4oGicIavmoB3eQsGV$DWSDmSWHbSFMqJwdd+8R0C53gHnbNVMNmQXxBaKWvqw=', max_length=128),
        ),
    ]
