# Generated by Django 5.0.6 on 2024-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mps", "0002_alter_memberofparliament_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberofparliament",
            name="image",
            field=models.URLField(
                default="https://img.freepik.com/free-vector/illustration-businessman_53876-5856.jpg?w=740&t=st=1719052890~\n        exp=1719053490~hmac=4e6f9ee8ae73ee004e482dc13a877e58d9dc91abcc31b2f6cfe9d878199eaba6",
            ),
        ),
    ]
