# Generated by Django 5.0.6 on 2024-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$s1vZsVr1IeIib5hYltjuMz$8UADh2akZ2sRpiP62YhdOm8xVI05t4LPe57dphMlm78=",
                max_length=128,
            ),
        ),
    ]
