# Generated by Django 5.0.6 on 2024-06-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0003_voter_username_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$9JmVj0oadkut7NTnhjYhdD$cyqPdRX7R9rfj5M6F56GJN1m48nlLkr67o2G4Ch0N2E=",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
