# Generated by Django 5.0.6 on 2024-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0004_alter_voter_password_alter_voter_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$j5YG4yb3AvmOAFAzgzwHMr$jvul/J1Vdqi7zC1WqS6r2nz+mSfl82+9/EENzE+u41w=",
                max_length=128,
            ),
        ),
    ]
