# Generated by Django 5.0.6 on 2024-06-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0005_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$aYpHOLWrUsekdcOnMEojWt$mM9QRwHGY90s7G0Pcb0U7G0PbZAi3SUbiXTnxdyet/g=",
                max_length=128,
            ),
        ),
    ]
