# Generated by Django 5.0.6 on 2024-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0007_alter_voter_options_remove_voter_id_voter_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$H3RQXJt3QAszLsBPUp0m2A$YZP6EXWohcmSwEpFs6yTA3JAOi85vyxaT+xclM+lQn4=",
                max_length=128,
            ),
        ),
    ]
