# Generated by Django 5.0.6 on 2024-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0008_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$JTDAZGUZbywtzmq9hzg1Bk$IQlHB4QJAtS0B4dKUE7b9W2XEA+qYXZh3/qQhppj2tY=",
                max_length=128,
            ),
        ),
    ]
