# Generated by Django 5.0.6 on 2024-07-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0008_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$yLEINieoEdXJbvkSgnXOxZ$TmHsDdij/JJFmHx1t6oCQKmwmM1Ev8Qj+dCCC7VusUM=",
                max_length=128,
            ),
        ),
    ]
