# Generated by Django 5.0.6 on 2024-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$9aWtCiZYU6kM9CiOfRW0Ic$LsHLsoTg4orcGxhe/tLUunUH12xvnE5YGgzhC+++KYk=', max_length=128),
        ),
    ]
