# Generated by Django 5.0.6 on 2024-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0010_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$4GBt558jHAt0Pp1w3UjY4q$QajkrrsRhq78axcLpoF/QeRRCg+rKJJhwjkXZJtkUq8=",
                max_length=128,
            ),
        ),
    ]
