# Generated by Django 5.0.6 on 2024-09-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0011_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$RpSSDFn6HZCNr5Wgu4lLMn$ssbCIuOwX0tJWc8jwYbXDyV++vqA4hBTwB8cLd4kiWk=",
                max_length=128,
            ),
        ),
    ]
