# Generated by Django 5.0.6 on 2024-09-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0012_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$FBFzEyOUFGTi7Qtk1MoC5F$YUpUpfSLLToLPqisCWGX5jxIpTf2CiW1esPhh3WmlFE=",
                max_length=128,
            ),
        ),
    ]
