# Generated by Django 5.0.6 on 2024-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0013_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$N3zBHZS8czK9ieq5LKAijZ$4xnCdy4UFkCLCDYrU8TqhqLbes316Cw6v4OK2KOO858=', max_length=128),
        ),
    ]
