# Generated by Django 5.0.6 on 2024-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_alter_voter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$9P1cADZKeiIgx4r474dg3J$eJmFk03pq5N9O25V6YnneGPdzEQho0E2Ry/0tVf4TsM=', max_length=128),
        ),
    ]
