# Generated by Django 5.0.6 on 2024-09-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter", "0015_alter_voter_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$24Unccq3zoKbk0KMJ3ZmSN$lspF4gisHl8sY4hu4A2qM2stPTWnQ14UwZcTqdyA/e8=",
                max_length=128,
            ),
        ),
    ]
