# Generated by Django 5.0.6 on 2024-09-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="comment",
            new_name="response",
        ),
    ]
